driver: torch
device: "cuda"

workdir:
  path: "/tmp/dist/sam_relational/"

distributed:
  backend: nccl
  type: single  # single or multiple
  nproc_per_node: 4
  single:
    init_method: tcp://127.0.0.1:23456

transforms:
  train: &train
    engine: "torchvision.transforms"
    ResizeLongestSide:
      size: 1024
    PadToSize:
      size: 1024
    # VHFlip:
  val:
    engine: "torchvision.transforms"
    ResizeLongestSide:
      size: 1024
  test:
    ResizeLongestSide:
      size: 1024
    # PadToSize:
    #   size: 1024

datasets:
  dataloader:
    batch_size: 8
    num_workers: 8
    shuffle: True
    collate_fn: "collate_data"
  coco:
    train1:
      bucket_name: &bucket "sr-shokunin"
      root: "perception/datasets/coco/train2017"
      anno_fn: "perception/datasets/coco/annotations/instances_train2017.json"
    train:
      bucket_name: "sr-shokunin"
      root: "perception/datasets/coco/val2017"
      anno_fn: "perception/datasets/coco/annotations/instances_val2017.json"
      instances_per_batch: -1

models:
  relational_network:
    sam_args:
      model: "default"
      checkpoint: "/root/krishneel/Documents/research/zero_shot/segment-anything/weights/sam_vit_h_4b8939.pth"

solvers:
  engine: 'torch.optim'
  SGD:
    lr: 0.001
    momentum: 0.9

io:
  s3_writer:
    engine: 's3_writer'
    bucket_name: 'sr-shokunin'
    root: 'perception/models/fsl/sam_relational/'

build:
  relational_network:
    dataset: "coco"
    weights: "s3://sr-shokunin/perception/models/fsl/sam_relational/model_0000017.pt"
    train:
      solver: "SGD"
      epochs: 100
    inference:
      transforms: "test"
      engine: "inference"
  
  model: "relational_network"
