_base_: "foreground_prototypes.yaml"

datasets:
  coco:
    val:
      bucket_name: "sr-shokunin"
      root: "perception/datasets/coco/train2017"
      anno_fn: "/root/krishneel/Downloads/coco/panoptic_train2017_only_stuffs.json"
      use_mask: True

io:
  file_io:
    root: "/root/krishneel/Downloads/fsl/prototypes/"
    per_class_avg: False

build:
  sam_fsod: &setup
    dataset: "coco"
    val:
      func: "bg_prototype_forward"
      event_handlers:
        collate_and_write:
          filename: "panoptic_train2017_only_stuffs.pkl"
          clean: True
          reduction: "inter_class_avg"
          cluster_size: 1000
  resnet_fsod:
    <<: *setup
  cie_fsod:
    <<: *setup
  dinov2_fsod:
    <<: *setup
  devit_dinov2_fsod:
    <<: *setup
