driver: torch
device: "cuda"

models:
  devit:
    sam_args:
      model: "vit_b"

datasets:
  dataloader:
    batch_size: 1
    num_workers: 0
    shuffle: False
    pin_memory: True
    collate_fn: "collate_data"
  coco:
    val:
      bucket_name: &bucket "sr-shokunin"
      root: "perception/datasets/coco/val2017"
      anno_fn: "perception/datasets/coco/annotations/instances_val2017.json"
  fs_coco:
    val:
      bucket_name: *bucket
      root: "perception/datasets/coco/train2017"
      json_file: "/root/krishneel/Downloads/coco/fs_coco_trainval_novel_5shot.json"

transforms:
  val:
    engine: "torchvision.transforms"
    ConvertFormatBoundingBox:
      old_fmt: "XYWH"
      new_fmt: "XYXY"
    ResizeLongestSide:
      size: 1024
    PadToSize:
      size: 1024

io:
  file_io:
    engine: 'prototype_writer'
    root: "/root/krishneel/Downloads/fsl/prototypes/"

build:
  devit:
    dataset: "fs_coco"
    val:
      func: "prototype_forward"
      transforms: "val"
      event_handlers:
        - collate_and_write:
            event_type: COMPLETED
            filename: "fs_coco_trainval_novel_5shot.pkl"

  model: "devit"
