device: "cuda"

workdir:
  path: "/tmp/fsl/sam_vitb_coco2017/"
  unique: False

distributed:
  nproc_per_node: 4

models:
  sam_fsod:
    sam_args:
      model: vit_b
    roi_pool_size: 7
    all_classes_fn: "../data/coco/all_classes.txt"
    seen_classes_fn: "../data/coco/seen_classes.txt"
    prototype_file: "/root/krishneel/Downloads/fsl/prototypes/devit_sam/sam_fsod/fg/fs_coco_trainval_novel_30shot.pkl"
    background_prototype_file: "/root/krishneel/Downloads/fsl/prototypes/devit_sam/sam_fsod/bg/panoptic_train2017_only_stuffs.pkl"

datasets:
  dataloader:
    batch_size: 16
    num_workers: 16
    collate_fn: "collate_data_instances"
  coco:
    train:
      bucket_name: &bucket "sr-shokunin"
      root: "perception/datasets/coco/train2017"
      anno_fn: "/root/krishneel/Downloads/fsl/fs_coco17_base_train.json"
    val:
      bucket_name: *bucket
      root: "perception/datasets/coco/val2017"
      anno_fn: "/root/krishneel/Downloads/fsl/fs_coco17_base_val.json"

transforms:
  train: &trans
    engine: "torchvision.transforms"
    ConvertFormatBoundingBox:
      old_fmt: "XYWH"
      new_fmt: "XYXY"
    VHFlip:
      hflip: True
      vflip: True
    ResizeLongestSide:
      size: 1024
    PadToSize:
      size: 1024
    ArgumentNoisyBBoxes:
      background_id: -1
    Normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
      
  val:
    <<: *trans
    VHFlip:
      hflip: False
      vflip: False
    ArgumentNoisyBBoxes:
      sample_size: 0

solvers:
  engine: "torch.optim"
  snapshot: 5000

  SGD:
    lr: 0.001
    momentum: 0.5
  schedulers:
    StepLR:
      step_size: 5
      gamma: 0.1

io:
  checkpoint:
    engine: 's3_writer'
    bucket_name: *bucket
    root: "perception/models/fsl/sam_vitb_coco17_30shot/"

build:
  sam_fsod:
    dataset: "coco"
    transforms: "train"
    train:
      solver: "SGD"
      scheduler: "StepLR"
      epochs: 50
    val:
      func: "default_val_forward"
      transforms: "val"

  model: "sam_fsod"

options:
  train: True
  eval: False
