_base_: "sam_vitb_trainval_30shot.yaml"
device: "cuda"

workdir:
  path: "/tmp/fsl/sam_vitb_5shot_coco2017/"

models:
  sam_fsod:
    prototype_file: "/root/krishneel/Downloads/fsl/prototypes/devit_sam/fs_coco_trainval_novel_5shot.pkl"
    background_prototype_file: "/root/krishneel/Downloads/fsl/prototypes/devit_sam/background/panoptic_train2017_only_stuffs.pkl"

io:
  checkpoint:
    root: "perception/models/fsl/sam_vitb_coco17_5shot/"
